version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: some_postgres_db
      POSTGRES_USER: some_postgres_user
      POSTGRES_PASSWORD: somepassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "9432:5432"
 
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: someemail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: somepassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data:

